name: CalculatingChat
version: '1.21.3-001'
main: ch.hatbe.calculatingChat.CalculatingChat
api-version: '1.21'
commands:
  nethercoordinates:
    description: Get the nether coordinates of a given overworld coordinate
    usage: /nethercoordinates <x> <z>
    aliases:
      - nc
      - nethercoords